<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

/**
 * Seeder pour le modèle Anime permettant d'ajouter les vraies données de l'application dans la base de données
 * @author Jonathan Carrière
 */
class AnimesSeeder
{
    public function run(): void
    {
        // Source : Les descriptions des animes proviennent de MyAnimeList. Les textes ont étés traduit de l'anglais au français via Google Translate. (https://myanimelist.net/)
        // Source : Les images des animes proviennent de Crunchyroll. (https://www.crunchyroll.com/)
        DB::table("animes")->insert([
            ["titre" => "A Silent Voice", "image" => "asilentvoice.jpg", "genre"=> "Drame", "description" => "Shouya Ishida a cherché à vaincre l'ennui de la manière la plus cruelle. Lorsque Shouko Nishimiya est transféré dans sa classe, Shouya et le reste de sa classe l'intimident sans réfléchir pour s'amuser. Cependant, lorsque sa mère informe l'école, il est pointé du doigt et blâmé pour tout ce qui lui a été fait. Regrettant sincèrement ses actions passées, il se lance dans un voyage de rédemption : rencontrer Shouko une fois de plus et faire amende honorable.", "studio" => "Kyoto Animation", "saisons" => 1, "episodes" => 5, "date_debut" => "2016-09-17", "duree_episode" => 30],
            ["titre" => "Bleach", "image" => "bleach.jpg", "genre"=> "Shonen", "description" => "Ichigo Kurosaki est un lycéen ordinaire, jusqu'à ce que sa famille soit attaquée par un Hollow, un esprit corrompu qui cherche à dévorer les âmes humaines. C'est alors qu'il rencontre une Soul Reaper nommée Rukia Kuchiki, qui se blesse en protégeant la famille d'Ichigo de l'agresseur. Pour sauver sa famille, Ichigo accepte l'offre de Rukia de prendre ses pouvoirs et devient ainsi un Soul Reaper.", "studio" => "Studio Pierrot", "saisons" => 16, "episodes" => 366, "date_debut" => "2004-10-05", "duree_episode" => 24],
            ["titre" => "Bocchi the Rock!", "image" => "bocchi.jpg", "genre"=> "Slice of Life", "description" => "Aspirant à se faire des amis et à joueur de la musique avec un groupe, Hitori 'Bocchi' Gotou, solitaire et socialement anxieuse, consacre son temps à jouer de la guitare. Un jour fatidique, Bocchi rencontre le batteur sortant Nijika Ijichi, qui l'invite à rejoindre le Kessoku Band lorsque leur guitariste, Ikuyo Kita, s'enfuit avant leur premier concert.", "studio" => "Clover Works", "saisons" => 1, "episodes" => 12, "date_debut" => "2022-10-09", "duree_episode" => 24],
            ["titre" => "Captain Harlock", "image" => "captainharlock.jpg", "genre"=> "Aventure", "description" => "Nous sommes en 2977 après JC et l'humanité est devenue stagnante. Les robots font tout le travail, les masses sont maintenues tranquilles par des messages subliminaux et les responsables gouvernementaux sont paresseux, ne se souciant que des activités récréatives comme le golf et les courses de chevaux. Le capitaine Herlock a défié cette mentalité insipide en dirigeant un groupe de rebelles partageant les mêmes idées.", "studio" => "Toei Animation", "saisons" => 1, "episodes" => 42, "date_debut" => "1978-03-14", "duree_episode" => 22],
            ["titre" => "Chainsaw Man", "image" => "chainsawman.jpg", "genre"=> "Action", "description" => "Denji est privé d'une vie d'adolescent normale, laissé avec rien d'autre que la dette écrasante de son père. Son seul compagnon est son animal de compagnie, le diable à la tronçonneuse Pochita, avec qui il tue des démons pour de l'argent qui finit inévitablement dans les poches des yakuzas. Tout ce que Denji peut faire, c'est rêver d'une bonne vie simple : une vie avec une cuisine délicieuse et une belle petite amie à ses côtés.", "studio" => "MAPPA", "saisons" => 1, "episodes" => 12, "date_debut" => "2022-10-12", "duree_episode" => 26],
            ["titre" => "Citrus", "image" => "citrus.jpg", "genre"=> "Romance", "description" => "Au cours de l'été de sa première année de lycée, la mère de Yuzu Aihara s'est remariée, la forçant à être transférée dans une nouvelle école. Pour une mondaine à la mode comme Yuzu, cet événement gênant n'est qu'une autre occasion de se faire de nouveaux amis, de tomber amoureux et enfin de vivre un premier baiser.", "studio" => "Passione", "saisons" => 1, "episodes" => 12, "date_debut" => "2018-01-06", "duree_episode" => 24],
            ["titre" => "Code Geass", "image" => "codegeass.jpg", "genre"=> "Mecha", "description" => "En 2010, le Saint Empire de Britannia s'impose comme une nation militaire dominante, à commencer par la conquête du Japon. Rebaptisé Zone 11 après sa défaite rapide, le Japon a connu une résistance importante contre ses tyrans dans une tentative de regagner son indépendance. Lelouch Lamperouge, un étudiant britannique, se retrouve malheureusement pris dans un feu croisé entre les forces armées britanniques et les rebelles de la zone 11.", "studio" => "Sunrise", "saisons" => 2, "episodes" => 50, "date_debut" => "2006-10-05", "duree_episode" => 24],
            ["titre" => "Death Note", "image" => "deathnote.jpg", "genre"=> "Shonen", "description" => "Les meurtres brutaux, les petits vols et la violence insensée polluent le monde humain. En revanche, le royaume des dieux de la mort est un tripot monotone et immuable. L'ingénieux étudiant japonais de 17 ans Light Yagami et le dieu sadique de la mort Ryuk partagent une croyance : leurs mondes sont pourris.", "studio" => "Madhouse", "saisons" => 1, "episodes" => 37, "date_debut" => "2006-10-04", "duree_episode" => 24],
            ["titre" => "Demon Slayer", "image" => "demon_slayer.jpg", "genre" => "Shonen", "description" => "Depuis la mort de son père, le fardeau de soutenir sa famille est tombé sur les épaules de Tanjirou Kamado. Un jour, Tanjirou décide de descendre au village local pour gagner un peu d'argent en vendant du charbon de bois. Sur le chemin du retour, la nuit tombante oblige Tanjirou à se réfugier dans la maison d'un homme étrange, qui l'avertit de l'existence de démons mangeurs de chair qui rôdent dans les bois la nuit.", "studio" => "Ufotable", "saisons" => 3, "episodes" => 12, "date_debut" => "2023-04-09", "duree_episode" => 24],
            ["titre" => "Domestic Girlfriend", "image" => "domestic.jpg", "genre"=> "Drame", "description" => "Pendant leur adolescence, peu de choses peuvent blesser les gens plus que les chagrins d'amour qui accompagnent un amour non partagé. C'est le cas de Natsuo Fujii, qui s'est retrouvé fasciné par Hina, l'enseignante toujours enjouée de son école. Dégonflé par ce désir inatteignable, Natsuo fait plaisir à ses amis et assiste à une table de mixage. Il y rencontre Rui, une fille dont le manque d'excitation rivalise avec lui-même.", "studio" => "Diomedéa", "saisons" => 1, "episodes" => 12, "date_debut" => "2019-01-12", "duree_episode" => 26],
            ["titre" => "Gintama", "image" => "gintama.jpg", "genre"=> "Shonen", "description" => "Edo est une ville qui abritait la vigueur et l'ambition des samouraïs à travers le pays. Cependant, après la reddition du Japon féodal à de puissants extraterrestres connus sous le nom d'Amanto, ces aspirations semblent désormais irréalisables. Avec le shogunat autrefois influent reconstruit en tant que gouvernement fantoche, une nouvelle loi est adoptée qui interdit rapidement toutes les épées en public.", "studio" => "Sunrise", "saisons" => 10, "episodes" => 367, "date_debut" => "2006-04-04", "duree_episode" => 24],
            ["titre" => "Higehiro", "image" => "higehiro.jpg", "genre"=> "Seinen", "description" => "Lorsque le salarié régulier Yoshida se réveille un dimanche matin après une longue nuit au bar, la dernière chose qu'il s'attend à voir, c'est que son petit appartement a un nouveau résident - une lycéenne inconnue. Après avoir noyé son chagrin au bar avec son bon ami Hashimoto, Yoshida est retourné chez lui dans une stupeur ivre, pour tomber sur Sayu Ogiwara, un lycéen en fuite.", "studio" => "Project No.9", "saisons" => 1, "episodes" => 12, "date_debut" => "2021-04-05", "duree_episode" => 20],
            ["titre" => "Hunter x Hunter", "image" => "hunterxhunter.jpg", "genre"=> "Shonen", "description" => "Les chasseurs se consacrent à l'accomplissement de tâches dangereuses, allant de la traversée des territoires inexplorés du monde à la localisation d'objets rares et de monstres. Avant de devenir chasseur, il faut réussir l'examen Hunter, un processus de sélection à haut risque dans lequel la plupart des candidats finissent handicapés ou, pire, morts.", "studio" => "Madhouse", "saisons" => 1, "episodes" => 148, "date_debut" => "2011-10-02", "duree_episode" => 24],
            ["titre" => "In Another World With My Smartphone", "image" => "smartphone.jpg", "genre" => "Isekai", "description" => "Dans une erreur irréfléchie, Dieu frappe accidentellement Touya Mochizuki avec un éclair égaré ! En guise d'excuse, Dieu lui offre un souhait et la chance de revivre dans un monde fantastique et magique. Touya accepte l'offre avec joie et, pour son seul souhait, ne demande qu'à garder son smartphone avec lui alors qu'il commence son voyage dans ce monde mystérieux.", "studio" => "Production Reed", "saisons" => 2, "episodes" => 12, "date_debut" => "2023-04-03", "duree_episode" => 25],
            ["titre" => "Jujutsu Kaisen", "image" => "jujutsukaisen.jpg", "genre"=> "Shonen", "description" => "Se livrant paresseusement à des activités paranormales sans fondement avec l'Occult Club, le lycéen Yuuji Itadori passe ses journées au club ou à l'hôpital, où il rend visite à son grand-père alité. Cependant, ce style de vie tranquille prend rapidement une tournure étrange lorsqu'il rencontre sans le savoir un objet maudit. Déclenchant une chaîne d'événements surnaturels, Yuuji se retrouve soudainement propulsé dans le monde des malédictions.", "studio" => "MAPPA", "saisons" => 1, "episodes" => 24, "date_debut" => "2020-10-03", "duree_episode" => 24],
            ["titre" => "Kaguya-sama: Love is War", "image" => "kaguya.jpg", "genre"=> "Slice of Life", "description" => "À la célèbre Académie Shuchiin, Miyuki Shirogane et Kaguya Shinomiya sont les meilleurs représentants du corps étudiant. Classé meilleur étudiant du pays et respecté par ses pairs et ses mentors, Miyuki est président du conseil étudiant. À ses côtés, la vice-présidente Kaguya, fille aînée de la riche famille Shinomiya, excelle dans tous les domaines imaginables.", "studio" => "A-1 Pictures", "saisons" => 3, "episodes" => 37, "date_debut" => "2019-01-12", "duree_episode" => 20],
            ["titre" => "KonoSuba: God's Blessing on This Wonderful World!", "image" => "konosuba.jpg", "genre"=> "Comédie", "description" => "Après une mort risible et pathétique en revenant d'avoir acheté un jeu, Kazuma Satou, lycéen et reclus, se retrouve assis devant une belle mais odieuse déesse nommée Aqua. Elle propose au gamer deux options : continuer vers le paradis ou se réincarner dans le rêve de chaque joueur : un véritable monde fantastique ! Choisissant de commencer une nouvelle vie, Kazuma est rapidement chargé de vaincre un roi démon qui terrorise les villages.", "studio" => "Studio Deen", "saisons" => 2, "episodes" => 20, "date_debut" => "2016-01-13", "duree_episode" => 24],
            ["titre" => "My Teen Romantic Comedy SNAFU", "image" => "myteenromantic.jpg", "genre"=> "Romance", "description" => "Hachiman Hikigaya est un lycéen apathique aux tendances narcissiques et semi-nihilistes. Il croit fermement que la jeunesse joyeuse n'est rien d'autre qu'une farce, et tous ceux qui disent le contraire ne font que se mentir. Dans une nouvelle punition pour avoir écrit un essai se moquant des relations sociales modernes, le professeur de Hachiman l'oblige à rejoindre le Volunteer Service Club, un club qui vise à tendre la main à tout élève qui cherche son soutien pour atteindre ses objectifs.", "studio" => "Brain's Base", "saisons" => 3, "episodes" => 40, "date_debut" => "2013-04-05", "duree_episode" => 22],
            ["titre" => "Naruto", "image" => "naruto.jpg", "genre"=> "Shonen", "description" => "Chaque fois que Naruto Uzumaki proclame qu'il deviendra un jour le Hokage - un titre décerné au meilleur ninja du Village Caché dans les Feuilles - personne ne le prend au sérieux. Depuis sa naissance, Naruto a été évité et ridiculisé par ses concitoyens. Mais leur mépris n'est pas dû au fait que Naruto est loquace, espiègle ou à cause de son incompétence dans les arts ninja, mais parce qu'il y a un démon en lui.", "studio" => "Studio Pierrot", "saisons" => 5, "episodes" => 220, "date_debut" => "2002-10-03", "duree_episode" => 22],
            ["titre" => "Neon Genesis Evangelion", "image" => "neongenesis.jpg", "genre"=> "Mecha", "description" => "Quinze ans après un événement cataclysmique connu sous le nom de Second Impact, le monde fait face à une nouvelle menace : des êtres célestes monstrueux appelés Anges envahissent Tokyo. L'humanité est incapable de se défendre contre les anges malgré l'utilisation de leurs armes et tactiques militaires les plus avancées. Le seul espoir pour le salut humain repose entre les mains de la NERV, une mystérieuse organisation dirigée par le froid Gendo Ikari.", "studio" => "Gainax", "saisons" => 1, "episodes" => 26, "date_debut" => "1995-10-04", "duree_episode" => 24],
            ["titre" => "Nier: Automata Ver1.1a", "image" => "nier.jpg", "genre"=> "Action", "description" => "Dans un monde post-apocalyptique envahi par des Machine Lifeforms fabriquées par des extraterrestres, l'humanité se prépare pour son dernier combat. Forcés de se retirer sur la Lune pour leur sécurité, les humains placent leurs espoirs sur un groupe d'androïdes artificiels connus sous le nom de soldats YoRHa. Dirigé par l'androïde de combat polyvalent YoRHa 2-gou B-gata 2B, le groupe se battra pour reprendre le contrôle de la Terre à ses envahisseurs.", "studio" => "A-1 Pictures", "saisons" => 1, "episodes" => 24, "date_debut" => "2023-01-08", "duree_episode" => 26],
            ["titre" => "One Punch Man", "image" => "onepunchman.jpg", "genre"=> "Shonen", "description" => "Saitama, apparemment peu impressionnant, a un passe-temps plutôt unique : être un héros. Afin de poursuivre son rêve d'enfant, Saitama s'est entraîné sans relâche pendant trois ans, perdant tous ses cheveux dans le processus. Maintenant, Saitama est si puissant qu'il peut vaincre n'importe quel ennemi d'un seul coup de poing. Cependant, n'avoir personne capable d'égaler sa force a conduit Saitama à un problème inattendu - il n'est plus capable de profiter du frisson de se battre et s'ennuie.", "studio" => "Madhouse", "saisons" => 2, "episodes" => 24, "date_debut" => "2015-10-05", "duree_episode" => 22],
            ["titre" => "Onimai", "image" => "onimai.jpg", "genre" => "Comédie", "description" => "L'autoproclamé \"gardien de sécurité à domicile\" Mahiro Oyama n'a pas quitté son domicile depuis des années, s'isolant dans sa chambre en jouant à des romans visuels. Ce mode de vie dépravé amène sa prodigieuse sœur, Mihari, à s'inquiéter pour son bien-être. Dans l'espoir de résoudre ce problème, elle élabore un plan pour le ramener à la normale.", "studio" => "Studio Bind", "saisons" => 1, "episodes" => 12, "date_debut" => "2023-02-05", "duree_episode" => 22],
            ["titre" => "Persona 4 Golden: The Animation", "image" => "persona4.jpg", "genre"=> "Action", "description" => "Loin de la ville, le temps s'écoule paisiblement dans cette commune rurale. Alors que les fleurs de cerisier se dispersent dans le vent, un jeune homme nommé Yu Narukami descend du train à la gare de Yasoinaba. Yu est venu dans cette ville, où vit son oncle, pour des raisons familiales ; il sera transféré au lycée local, Yasogami High. Ainsi commence sa vie scolaire...", "studio" => "A-1 Pictures", "saisons" => 1, "episodes" => 12, "date_debut" => "2014-07-10", "duree_episode" => 24],
            ["titre" => "Rascal Does Not Dream of Bunny Girl Senpai", "image" => "rascal.jpg", "genre"=> "Seinen", "description" => "Le rare et inexplicable syndrome de la puberté est considéré comme un mythe. C'est une maladie rare qui n'affecte que les adolescents et ses symptômes sont si surnaturels que presque personne ne le reconnaît comme un événement légitime. Cependant, le lycéen Sakuta Azusagawa sait par expérience personnelle que c'est très réel et qu'il se trouve être assez répandu dans son école.", "studio" => "CloverWorks", "saisons" => 1, "episodes" => 13, "date_debut" => "2018-10-04", "duree_episode" => 24],
            ["titre" => "Re: Zero - Starting Life in Another World", "image" => "rezero.jpg", "genre"=> "Aventure", "description" => "Lorsque Subaru Natsuki quitte le dépanneur, la dernière chose à laquelle il s'attend est d'être arraché à sa vie quotidienne et plongé dans un monde fantastique. Les choses ne vont pas bien pour l'adolescent perplexe; cependant, peu de temps après son arrivée, il est attaqué par des voyous. Armé seulement d'un sac d'épicerie et d'un téléphone portable désormais inutile, il est rapidement réduit en bouillie.", "studio" => "White Fox", "saisons" => 2, "episodes" => 50, "date_debut" => "2016-04-04", "duree_episode" => 22],
            ["titre" => "Steins;Gate", "image" => "steingate.jpg", "genre"=> "Drame", "description" => "Le scientifique excentrique Rintarou Okabe a une soif sans fin d'exploration scientifique. Avec son idiot d'ami, mais bien intentionné Mayuri Shiina et son colocataire Itaru Hashida, Rintarou fonde le Future Gadget Laboratory dans l'espoir de créer des innovations technologiques qui déroutent la psyché humaine. Malgré les prétentions de grandeur, le seul gadget notable que le trio a créé est un micro-ondes qui a le pouvoir mystificateur de transformer les bananes en glu verte.", "studio" => "White Fox", "saisons" => 1, "episodes" => 24, "date_debut" => "2011-04-06", "duree_episode" => 22],
            ["titre" => "Sword Art Online", "image" => "swordartonline.jpg", "genre"=> "Action", "description" => "Depuis la sortie de l'innovant NerveGear, les joueurs du monde entier ont eu l'opportunité de découvrir la réalité virtuelle complètement immersive. Sword Art Online (SAO), l'un des jeux les plus récents sur cette console VR, offre une passerelle vers le monde merveilleux d'Aincrad, un paysage médiéval vivant où les utilisateurs peuvent faire n'importe quoi dans les limites de leur imagination. Avec la sortie de cette sensation mondiale, le jeu n'a jamais été aussi réaliste.", "studio" => "A-1 Pictures", "saisons" => 4, "episodes" => 96, "date_debut" => "2012-07-08", "duree_episode" => 20],
            ["titre" => "Tekkaman Blade", "image" => "tekkaman.jpg", "genre"=> "Mecha", "description" => "Tekkaman Blade se déroule en l'an 2300 après JC. À un certain moment, le Radam attaque la terre. Quelques mois après le début de l'invasion, un tekkaman apparaît, il se fait appeler Blade et avec l'aide des Space Knights, Blade commence à combattre le Radam. Mais il y a certaines choses que Blade ne dit pas sur son passé.", "studio" => "Tatsunoko", "saisons" => 1, "episodes" => 50, "date_debut" => "1992-02-18", "duree_episode" => 18],
            ["titre" => "That Time I Got Reincarnated As A Slime", "image" => "slime.jpg", "genre"=> "Shonen", "description" => "La nation de Tempest est d'humeur festive après avoir surmonté avec succès l'attaque surprise de l'armée de Falmuth et de la Sainte Église occidentale. Au-delà des festivités se cache une rencontre entre Tempest et ses alliés pour décider de l'avenir de la Nation des Monstres. Avec les conséquences de l'invasion de Falmuth, le comportement suspect de Milim Nava et la disparition du Demon Lord Carrion, les problèmes semblent continuer à s'accumuler.", "studio" => "Eight Bit", "saisons" => 2, "episodes" => 48, "date_debut" => "2018-10-05", "duree_episode" => 24],
            ["titre" => "The Disastrous Life of Saiki K.", "image" => "saiki.jpg", "genre"=> "Comédie", "description" => "Pour une personne moyenne, les capacités psychiques peuvent sembler une bénédiction ; pour Kusuo Saiki, cependant, cela ne pourrait pas être plus éloigné de la vérité. Doté d'un large éventail de capacités surnaturelles allant de la télépathie à la vision aux rayons X, il trouve que cette soi-disant bénédiction n'est rien d'autre qu'une malédiction.", "studio" => "J.C Staff", "saisons" => 3, "episodes" => 50, "date_debut" => "2016-10-04", "duree_episode" => 24],
            ["titre" => "The Quintessential Quintuplets", "image" => "quintuplets.jpg", "genre"=> "Romance", "description" => "Grâce aux diligents conseils de leur tuteur Fuutarou Uesugi, les résultats scolaires des quintuplés Nakano montrent des signes d'amélioration, même si leur chemin vers l'obtention du diplôme est encore semé d'embûches. Cependant, alors qu'ils continuent de provoquer diverses situations qui retardent tout tutorat réel, Fuutarou s'implique de plus en plus dans leur vie personnelle, compliquant davantage leur relation les unes avec les autres.", "studio" => "Tezuka Productions", "saisons" => 2, "episodes" => 24, "date_debut" => "2019-01-09", "duree_episode" => 24],
            ["titre" => "The Rising of the Shield Hero", "image" => "shieldhero.jpg", "genre"=> "Seinen", "description" => "Les quatre héros cardinaux sont un groupe de jeunes ordinaires du Japon moderne réincarnés dans le royaume de Melromarc pour en devenir les sauveurs. Melromarc est un pays en proie aux Vagues de la catastrophes qui ont à plusieurs reprises ravagé la terre et apporté le désastre à ses citoyens pendant des siècles. Les quatre héros reçoivent respectivement une épée, une lance, un arc et un bouclier pour vaincre ces vagues. Naofumi Iwatani, un otaku, devient maudit d'être le Héros au bouclier.", "studio" => "Kinema Citrus DR Movie", "saisons" => 2, "episodes" => 36, "date_debut" => "2019-01-09", "duree_episode" => 22],
            ["titre" => "UFO Robot Grendizer", "image" => "grendizer.jpg", "genre"=> "Mecha", "description" => "Duke Fleed est un survivant de la planète fuie qui s'est échappé sur Terre, à bord d'un mystérieux vaisseau spatial, où il est élevé par le Dr Umon comme son fils adoptif, et connu sous le nom de Daisuke Umon. Des années après son arrivée, il est confronté à la menace du roi Vega et de son armée, qui veulent conquérir la Terre. Avec ses amis Koji et Hikaru (et plus tard sa sœur cadette Maria Grace), Duke décide de riposter en utilisant sa meilleure arme - le tout-puissant Goldorak.", "studio" => "Toei Animation", "saisons" => 1, "episodes" => 74, "date_debut" => "1975-10-05", "duree_episode" => 18],
            ["titre" => "Vinland Saga", "image" => "vinland_saga.jpg", "genre" => "Action", "description" => "Après la mort de son père et la destruction de son village aux mains des pillards anglais, Einar souhaite une vie paisible avec sa famille dans leurs fermes nouvellement reconstruites. Cependant, le destin a d'autres plans : son village est à nouveau envahi. Einar regarde, impuissant, les maraudeurs danois brûler ses terres et massacrer sa famille. Les envahisseurs capturent Einar et le ramènent au Danemark comme esclave.", "studio" => "MAPPA", "saisons" => 2, "episodes" => 24, "date_debut" => "2023-02-10", "duree_episode" => 24],
            ["titre" => "Your Name", "image" => "yourname.jpg", "genre"=> "Drame", "description" => "Mitsuha Miyamizu, une lycéenne, aspire à vivre la vie d'un garçon dans la ville animée de Tokyo. Pendant ce temps dans la ville, Taki Tachibana mène une vie bien remplie en tant que lycéen tout en jonglant avec son travail à temps partiel et espère un avenir dans l'architecture. Un jour, Mitsuha se réveille dans une chambre qui n'est pas la sienne et se retrouve soudain à vivre la vie de rêve à Tokyo, mais dans le corps de Taki!", "studio" => "CoMix Wave Films", "saisons" => 1, "episodes" => 4, "date_debut" => "2016-08-26", "duree_episode" => 30]
        ]);
    }
}
