<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

/**
 * Seeder pour la table AnimePlateformes permettant d'ajouter les vraies données de l'application dans la base de données
 * @author Jonathan Carrière
 */
class AnimesPlateformesSeeder
{
    public function run(): void
    {
        DB::table("plateformes_animes")->insert([
            ["anime_id" => 1, "plateforme_id" => 1],
            ["anime_id" => 2, "plateforme_id" => 1],
            ["anime_id" => 3, "plateforme_id" => 1],
            ["anime_id" => 4, "plateforme_id" => 1],
            ["anime_id" => 5, "plateforme_id" => 1],
            ["anime_id" => 6, "plateforme_id" => 1],
            ["anime_id" => 7, "plateforme_id" => 1],
            ["anime_id" => 8, "plateforme_id" => 1],
            ["anime_id" => 9, "plateforme_id" => 1],
            ["anime_id" => 10, "plateforme_id" => 1],
            ["anime_id" => 11, "plateforme_id" => 1],
            ["anime_id" => 12, "plateforme_id" => 1],
            ["anime_id" => 13, "plateforme_id" => 1],
            ["anime_id" => 14, "plateforme_id" => 1],
            ["anime_id" => 15, "plateforme_id" => 1],
            ["anime_id" => 16, "plateforme_id" => 1],
            ["anime_id" => 17, "plateforme_id" => 1],
            ["anime_id" => 18, "plateforme_id" => 1],
            ["anime_id" => 19, "plateforme_id" => 1],
            ["anime_id" => 20, "plateforme_id" => 1],
            ["anime_id" => 21, "plateforme_id" => 1],
            ["anime_id" => 22, "plateforme_id" => 1],
            ["anime_id" => 23, "plateforme_id" => 1],
            ["anime_id" => 24, "plateforme_id" => 1],
            ["anime_id" => 25, "plateforme_id" => 1],
            ["anime_id" => 26, "plateforme_id" => 1],
            ["anime_id" => 27, "plateforme_id" => 1],
            ["anime_id" => 28, "plateforme_id" => 1],
            ["anime_id" => 29, "plateforme_id" => 1],
            ["anime_id" => 30, "plateforme_id" => 1],
            ["anime_id" => 31, "plateforme_id" => 1],
            ["anime_id" => 32, "plateforme_id" => 1],
            ["anime_id" => 33, "plateforme_id" => 1],
            ["anime_id" => 34, "plateforme_id" => 1],
            ["anime_id" => 35, "plateforme_id" => 1],
            ["anime_id" => 36, "plateforme_id" => 1],
            ["anime_id" => 1, "plateforme_id" => 2],
            ["anime_id" => 3, "plateforme_id" => 2],
            ["anime_id" => 5, "plateforme_id" => 2],
            ["anime_id" => 7, "plateforme_id" => 2],
            ["anime_id" => 9, "plateforme_id" => 2],
            ["anime_id" => 11, "plateforme_id" => 2],
            ["anime_id" => 13, "plateforme_id" => 2],
            ["anime_id" => 15, "plateforme_id" => 2],
            ["anime_id" => 17, "plateforme_id" => 2],
            ["anime_id" => 19, "plateforme_id" => 2],
            ["anime_id" => 21, "plateforme_id" => 2],
            ["anime_id" => 23, "plateforme_id" => 2],
            ["anime_id" => 25, "plateforme_id" => 2],
            ["anime_id" => 27, "plateforme_id" => 2],
            ["anime_id" => 29, "plateforme_id" => 2],
            ["anime_id" => 31, "plateforme_id" => 2],
            ["anime_id" => 33, "plateforme_id" => 2],
            ["anime_id" => 35, "plateforme_id" => 2],
            ["anime_id" => 2, "plateforme_id" => 3],
            ["anime_id" => 4, "plateforme_id" => 3],
            ["anime_id" => 6, "plateforme_id" => 3],
            ["anime_id" => 8, "plateforme_id" => 3],
            ["anime_id" => 10, "plateforme_id" => 3],
            ["anime_id" => 12, "plateforme_id" => 3],
            ["anime_id" => 14, "plateforme_id" => 3],
            ["anime_id" => 16, "plateforme_id" => 3],
            ["anime_id" => 18, "plateforme_id" => 3],
            ["anime_id" => 20, "plateforme_id" => 3],
            ["anime_id" => 22, "plateforme_id" => 3],
            ["anime_id" => 24, "plateforme_id" => 3],
            ["anime_id" => 26, "plateforme_id" => 3],
            ["anime_id" => 28, "plateforme_id" => 3],
            ["anime_id" => 30, "plateforme_id" => 3],
            ["anime_id" => 32, "plateforme_id" => 3],
            ["anime_id" => 34, "plateforme_id" => 3],
            ["anime_id" => 36, "plateforme_id" => 3],
            ["anime_id" => 1, "plateforme_id" => 5],
            ["anime_id" => 5, "plateforme_id" => 5],
            ["anime_id" => 10, "plateforme_id" => 5],
            ["anime_id" => 15, "plateforme_id" => 5],
            ["anime_id" => 20, "plateforme_id" => 5],
            ["anime_id" => 25, "plateforme_id" => 5],
            ["anime_id" => 30, "plateforme_id" => 5],
            ["anime_id" => 35, "plateforme_id" => 5],
            ["anime_id" => 2, "plateforme_id" => 4],
            ["anime_id" => 3, "plateforme_id" => 4],
            ["anime_id" => 5, "plateforme_id" => 4],
            ["anime_id" => 7, "plateforme_id" => 4],
            ["anime_id" => 11, "plateforme_id" => 4],
            ["anime_id" => 13, "plateforme_id" => 4],
            ["anime_id" => 17, "plateforme_id" => 4],
            ["anime_id" => 19, "plateforme_id" => 4],
            ["anime_id" => 23, "plateforme_id" => 4],
            ["anime_id" => 29, "plateforme_id" => 4],
            ["anime_id" => 31, "plateforme_id" => 4]
        ]);
    }
}
