<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

/**
 * Seeder pour le modèle Horaire permettant d'ajouter les vraies données de l'application dans la base de données
 * @author Jonathan Carrière
 */
class HorairesSeeder
{
    public function run(): void
    {
        DB::table("horaires")->insert([
            ["anime_id" => 1, "user_id" => 1],
            ["anime_id" => 3, "user_id" => 1],
            ["anime_id" => 5, "user_id" => 1],
            ["anime_id" => 7, "user_id" => 1],
            ["anime_id" => 9, "user_id" => 1],
            ["anime_id" => 11, "user_id" => 1],
            ["anime_id" => 13, "user_id" => 1],
            ["anime_id" => 15, "user_id" => 1],
            ["anime_id" => 17, "user_id" => 1],
            ["anime_id" => 19, "user_id" => 1],
            ["anime_id" => 21, "user_id" => 1],
            ["anime_id" => 23, "user_id" => 1],
            ["anime_id" => 25, "user_id" => 1],
            ["anime_id" => 27, "user_id" => 1],
            ["anime_id" => 29, "user_id" => 1],
            ["anime_id" => 31, "user_id" => 1],
            ["anime_id" => 33, "user_id" => 1],
            ["anime_id" => 35, "user_id" => 1],
            ["anime_id" => 2, "user_id" => 2],
            ["anime_id" => 4, "user_id" => 2],
            ["anime_id" => 6, "user_id" => 2],
            ["anime_id" => 8, "user_id" => 2],
            ["anime_id" => 10, "user_id" => 2],
            ["anime_id" => 12, "user_id" => 2],
            ["anime_id" => 14, "user_id" => 2],
            ["anime_id" => 16, "user_id" => 2],
            ["anime_id" => 18, "user_id" => 2],
            ["anime_id" => 20, "user_id" => 2],
            ["anime_id" => 22, "user_id" => 2],
            ["anime_id" => 24, "user_id" => 2],
            ["anime_id" => 26, "user_id" => 2],
            ["anime_id" => 28, "user_id" => 2],
            ["anime_id" => 30, "user_id" => 2],
            ["anime_id" => 32, "user_id" => 2],
            ["anime_id" => 34, "user_id" => 2],
            ["anime_id" => 36, "user_id" => 2],
            ["anime_id" => 2, "user_id" => 3],
            ["anime_id" => 9, "user_id" => 3],
            ["anime_id" => 11, "user_id" => 3],
            ["anime_id" => 31, "user_id" => 3],
            ["anime_id" => 32, "user_id" => 3],
            ["anime_id" => 2, "user_id" => 4],
            ["anime_id" => 4, "user_id" => 4],
            ["anime_id" => 5, "user_id" => 4],
            ["anime_id" => 11, "user_id" => 4],
            ["anime_id" => 16, "user_id" => 4],
            ["anime_id" => 18, "user_id" => 4],
            ["anime_id" => 21, "user_id" => 4],
            ["anime_id" => 23, "user_id" => 4],
            ["anime_id" => 25, "user_id" => 4],
            ["anime_id" => 30, "user_id" => 4],
            ["anime_id" => 31, "user_id" => 4],
            ["anime_id" => 36, "user_id" => 4],
            ["anime_id" => 1, "user_id" => 5],
            ["anime_id" => 7, "user_id" => 5],
            ["anime_id" => 6, "user_id" => 5],
            ["anime_id" => 12, "user_id" => 5],
            ["anime_id" => 15, "user_id" => 5],
            ["anime_id" => 19, "user_id" => 5],
            ["anime_id" => 20, "user_id" => 5],
            ["anime_id" => 22, "user_id" => 5],
            ["anime_id" => 27, "user_id" => 5],
            ["anime_id" => 28, "user_id" => 5],
            ["anime_id" => 3, "user_id" => 6],
            ["anime_id" => 9, "user_id" => 6],
            ["anime_id" => 11, "user_id" => 6],
            ["anime_id" => 12, "user_id" => 6],
            ["anime_id" => 15, "user_id" => 6],
            ["anime_id" => 17, "user_id" => 6],
            ["anime_id" => 19, "user_id" => 6],
            ["anime_id" => 22, "user_id" => 6],
            ["anime_id" => 26, "user_id" => 6],
            ["anime_id" => 27, "user_id" => 6],
            ["anime_id" => 31, "user_id" => 6],
            ["anime_id" => 34, "user_id" => 6],
            ["anime_id" => 4, "user_id" => 7],
            ["anime_id" => 5, "user_id" => 7],
            ["anime_id" => 9, "user_id" => 7],
            ["anime_id" => 10, "user_id" => 7],
            ["anime_id" => 11, "user_id" => 7],
            ["anime_id" => 16, "user_id" => 7],
            ["anime_id" => 18, "user_id" => 7],
            ["anime_id" => 20, "user_id" => 7],
            ["anime_id" => 25, "user_id" => 7],
            ["anime_id" => 29, "user_id" => 7],
            ["anime_id" => 10, "user_id" => 8],
            ["anime_id" => 11, "user_id" => 8],
            ["anime_id" => 15, "user_id" => 8],
            ["anime_id" => 17, "user_id" => 8],
            ["anime_id" => 18, "user_id" => 8],
            ["anime_id" => 20, "user_id" => 8],
            ["anime_id" => 24, "user_id" => 8],
            ["anime_id" => 26, "user_id" => 8],
            ["anime_id" => 27, "user_id" => 8],
            ["anime_id" => 28, "user_id" => 8],
            ["anime_id" => 30, "user_id" => 8],
            ["anime_id" => 32, "user_id" => 8],
            ["anime_id" => 3, "user_id" => 9],
            ["anime_id" => 5, "user_id" => 9],
            ["anime_id" => 6, "user_id" => 9],
            ["anime_id" => 14, "user_id" => 9],
            ["anime_id" => 19, "user_id" => 9],
            ["anime_id" => 22, "user_id" => 9],
            ["anime_id" => 23, "user_id" => 9],
            ["anime_id" => 26, "user_id" => 9],
            ["anime_id" => 27, "user_id" => 9],
            ["anime_id" => 28, "user_id" => 9],
            ["anime_id" => 36, "user_id" => 9],
            ["anime_id" => 7, "user_id" => 10],
            ["anime_id" => 8, "user_id" => 10],
            ["anime_id" => 11, "user_id" => 10],
            ["anime_id" => 15, "user_id" => 10],
            ["anime_id" => 19, "user_id" => 10],
            ["anime_id" => 20, "user_id" => 10],
            ["anime_id" => 22, "user_id" => 10],
            ["anime_id" => 25, "user_id" => 10],
            ["anime_id" => 28, "user_id" => 10],
            ["anime_id" => 29, "user_id" => 10],
            ["anime_id" => 31, "user_id" => 10],
            ["anime_id" => 1, "user_id" => 11],
            ["anime_id" => 5, "user_id" => 11],
            ["anime_id" => 10, "user_id" => 11],
            ["anime_id" => 20, "user_id" => 11],
            ["anime_id" => 30, "user_id" => 11],
            ["anime_id" => 1, "user_id" => 12],
            ["anime_id" => 5, "user_id" => 12],
            ["anime_id" => 10, "user_id" => 12],
            ["anime_id" => 20, "user_id" => 12],
            ["anime_id" => 30, "user_id" => 12],
            ["anime_id" => 2, "user_id" => 13],
            ["anime_id" => 9, "user_id" => 13],
            ["anime_id" => 11, "user_id" => 13],
            ["anime_id" => 31, "user_id" => 13],
            ["anime_id" => 32, "user_id" => 13]
        ]);
    }
}
