<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

/**
 * Seeder pour le modèle Personnage permettant d'ajouter les vraies données de l'application dans la base de données
 * @author Jonathan Carrière
 */
class PersonnagesSeeder
{
    public function run(): void
    {
        // Source : Les descriptions et images des personnages proviennent de MyAnimeListe. Les textes ont étés traduit de l'anglais au français via Google Translate. (https://myanimelist.net/)
        DB::table("personnages")->insert([
            ["nom" => "2B", "anime_id" => 21, "doubleurs_id" => 9, "image" => "2b.jpg", "description" => "Un androïde YoRHa créé pour combattre les formes de vie mécaniques qui ont envahi la planète au nom des humains survivants."],
            ["nom" => "Agatsuma Zenitsu", "anime_id" => 9, "doubleurs_id" => null, "image" => "zenitsu.jpg", "description" => "Zenitsu Agatsuma est membre du Demon Killing Corps et compagnon de voyage de Kamado Tanjirou."],
            ["nom" => "Akaza", "anime_id" => 9, "doubleurs_id" => 8, "image" => "akaza.jpg", "description" => "Akaza est membre des Douze Lunes Démoniaques, occupant le poste de Upper Moon Three."],
            ["nom" => "Berg L'Arc", "anime_id" => 33, "doubleurs_id" => 2, "image" => "larc.jpg", "description" => "Il est insouciant et décontracté, prenant un chemin très détendu pour chaque problème. Il est, selon Naofumi, un type de personnage de frère aîné. Même s'il est devenu roi, il aime sa liberté. Tout comme Glass, il a un esprit guerrier qui se manifeste lors de son combat avec Naofumi."],
            ["nom" => "C. C.", "anime_id" => 7, "doubleurs_id" => 24, "image" => "cc.jpg", "description" => "CC est sérieux, solennel et émotionnellement coupé du monde. Pour avoir été trahie dans le passé, elle sent qu'elle ne peut établir de lien significatif avec personne et ne s'allie qu'avec les autres par désir pragmatique d'atteindre son objectif de mettre fin à sa propre vie. Malgré cela, son temps avec Lelouch lui permet de commencer à briser ses barrières émotionnelles."],
            ["nom" => "Denji 'Chainsaw Man'", "anime_id" => 5, "doubleurs_id" => 22, "image" => "denji.jpg", "description" => "En tant que jeune garçon, Denji hérite des dettes de son père envers les Yakuza. Après avoir rencontré Pochita, il devient un Devil Hunter pour les Yakuza dans le but d'effacer sa dette. Après que Denji ait été trahi et assassiné par les Yakuza, qui étaient sous le contrôle d'un diable, Pochita a ramené Denji à la vie en devenant son cœur. Il a maintenant la capacité de devenir un hybride diable et humain en tirant sur le cordon de sa poitrine."],
            ["nom" => "Elnea Ortlinde Sushie", "anime_id" => 14, "doubleurs_id" => null, "image" => "sushie.jpg", "description" => "Aucune description est présente pas ce personnage..."],
            ["nom" => "Elze Shileska", "anime_id" => 14, "doubleurs_id" => null, "image" => "elze.jpg", "description" => "Elze est une aventurière équipée de gantelets aux deux mains. Elle est du genre à agir plutôt qu'à parler et intervient souvent avant de réfléchir. Elle est la plus âgée des jumelles."],
            ["nom" => "Emilia", "anime_id" => 26, "doubleurs_id" => 21, "image" => "emilia.jpg", "description" => "C'est une fille demi-elfe aux cheveux argentés qui est l'une des candidates pour devenir le prochain dirigeant aux élections royales. Subaru la rencontre pour la première fois lorsque son insigne est volé par Felt car elle doit le posséder pour pouvoir participer aux élections. Elle se présente comme Satella lorsqu'elle et Subaru se sont rencontrés lors de la première chronologie avant de se présenter par son vrai nom lorsqu'elle a récupéré son insigne."],
            ["nom" => "Filo", "anime_id" => 33, "doubleurs_id" => 6, "image" => "filo.jpg", "description" => "Filo a grandi à un rythme anormalement rapide et en quelques jours seulement, elle est devenue une Filoliale complètement développée, se transformant plus tard en une espèce rare de Filolial Queen où elle a ensuite reçu la capacité de se transformer en une forme humanoïde ressemblant fortement à un ange et la capacité de parler. en raison de son association avec le Shield Hero."],
            ["nom" => "Fox Devil", "anime_id" => 5, "doubleurs_id" => 10, "image" => "fox.jpg", "description" => "Le Fox Devil figure parmi les démons les plus puissants du Japon. Le chasseur de démon peuvent créer un contrat avec cette bête afin de pouvoir emprunter ses pouvoirs en échange d'un sacrifice. Le Fox Devil est connue pour sa capacité de consommer sa proie en une seule bouchée."],
            ["nom" => "Gintoki Sakata", "anime_id" => 11, "doubleurs_id" => 20, "image" => "gintoki.jpg", "description" => "Gintoki est un samouraï vivant à une époque où les samouraïs ne sont plus nécessaires. Pour ajouter à ses problèmes, des extraterrestres oppressifs se sont installés pour envahir la planète Terre. Gintoki travaille en prenant des petits boulots aux côtés de deux enfants : Kagura et Shinpachi. Pendant la guerre de Joui, il était connu sous le nom de 'Diable blanc' (Shiroyasha) en raison de ses cheveux argentés et de ses vêtements blancs qu'il portait au combat."],
            ["nom" => "Gon Freecss", "anime_id" => 13, "doubleurs_id" => 4, "image" => "gon.jpg", "description" => "Gon veut devenir chasseur parce qu'il souhaite découvrir les profondeurs d'une profession qui amènerait un père à choisir la profession plutôt que d'être avec son propre fils.Gon est un garçon athlétique, rustique et amical qui recherche l'aventure. De plus, il n'est pas très bon en maths. Cependant, ayant passé beaucoup de temps dans les bois étant enfant, il est très doué avec les animaux. En même temps, ses défauts résident dans son tempérament et sa nature impulsive."],
            ["nom" => "Hashibira Inasuke", "anime_id" => 9, "doubleurs_id" => null, "image" => "inosuke.jpg", "description" => "Inosuke est membre du Demon Slayer Corps et compagnon de voyage de Tanjirou Kamado. On le voit souvent coiffé d'une tête de sanglier."],
            ["nom" => "Hitori 'Bocchi' Gotou", "anime_id" => 3, "doubleurs_id" => 1, "image" => "bocchi.jpg", "description" => "Une étudiante de première année solitaire et socialement anxieux. Elle se décrit comme une habitante de l'intérieur. Elle aspire à rejoindre un groupe et à devenir populaire, et commence donc à jouer de la guitare.Elle devient la guitariste principale du Kessoku Band. Son talent est phénoménal, mais elle ne peut pas bien le montrer dans un groupe ou en public."],
            ["nom" => "Hoto Cocoa", "anime_id" => null, "doubleurs_id" => null, "image" => "cocoa.jpg", "description" => "Kokoa est une fille très excitante avec une disposition pétillante et une dent sucrée. Elle est aussi très maladroite et entêtée, causant de nombreux accidents. Elle est toujours souriante et optimiste avec une forte détermination à faire de son mieux avec tout ce que la vie lui réserve, et son enthousiasme débridé convainc généralement les autres d'essayer de nouvelles choses."],
            ["nom" => "Ijichi Nijika", "anime_id" => 3, "doubleurs_id" => null, "image" => "Ijichi.jpg", "description" => "Un élève de deuxième année énergique et joyeux. Elle est la batteuse du Kessoku Band. L'organisatrice de son groupe qui s'occupe d'Hitori a déjà rejoint le Kessoku Band. Elle a une sœur aînée, Seika, qui est la gérante de la maison \"STARRY\" et a un sentiment particulier pour la maison."],
            ["nom" => "Ishida Shouya", "anime_id" => 1, "doubleurs_id" => null, "image" => "shouya.jpg", "description" => "Le personnage principal et le narrateur. Ishida a intimidé Nishimiya Shouko à l'école primaire et lorsqu'elle a été transférée, il a été ostracisé et intimidé par ses anciens amis. Il a commencé à ignorer ceux qui l'entouraient (les imaginant avec un grand X sur le visage) et a été poussé au suicide. Il a changé d'avis après s'être excusé auprès de Nishimiya et a commencé à passer du temps avec elle."],
            ["nom" => "Jouga Maya", "anime_id" => null, "doubleurs_id" => null, "image" => "maya.jpg", "description" => "L'un des amis d'école de Chino. Maya est très excitable et espiègle. Elle est également énergique et optimiste, mais peut être assez franche avec ses amis. Elle semble admirer Rize."],
            ["nom" => "Kafuu Chino", "anime_id" => null, "doubleurs_id" => 14, "image" => "chino.jpg", "description" => "La petite-fille du propriétaire de la Rabbit House. Une fille à la voix douce qui se réchauffe lentement avec Cocoa, bien qu'elle soit souvent agacée par son insistance à être appelée «grande sœur». Avec son père, elle est la seule à connaître le secret concernant Tippy et son grand-père. Chino agit avec beaucoup plus de maturité que son âge et est normalement le membre le plus responsable et le plus organisé du Rabbit House Café."],
            ["nom" => "Kamado Nezuko", "anime_id" => 9, "doubleurs_id" => 12, "image" => "nezuko.jpg", "description" => "Nezuko est la soeur de Tanjirou."],
            ["nom" => "Kamado Tanjiro", "anime_id" => 9, "doubleurs_id" => 5, "image" => "tanjiro.jpg", "description" => "Tanjirou Kamado est le principal protagoniste de Kimetsu no Yaiba, qui devient un chasseur de démons et rejoint le Demon Killing Corps pour traquer le démon qui a assassiné sa famille et transformé sa sœur Nezuko en démon."],
            ["nom" => "Killua Zoldyck", "anime_id" => 13, "doubleurs_id" => 7, "image" => "killua.jpg", "description" => "Killua est présenté comme un personnage similaire à Gon : effronté, joyeux et plein de mauvaises idées. Cependant, contrairement à la politesse de Gon, Killua peut être assez impoli envers les autres, principalement les étrangers et les personnes âgées. Il est également l'un des personnages les plus rapides et analyse souvent une situation avec une grande facilité et précision."],
            ["nom" => "Kirima Sharo", "anime_id" => null, "doubleurs_id" => null, "image" => "sharo.jpg", "description" => "L'amie d'enfance de Chiya qui vit à côté de l'Ama Usa An et travaille dans un café de tisane, Fleur de Lapin. Sharo est une fille sensible et timide qui a des insécurités en ce qui concerne son image. Elle est facilement troublée et s'inquiète que ses amis pensent qu'elle est une femme riche et sophistiquée alors qu'en réalité, elle est une fille ordinaire vivant dans une maison humble."],
            ["nom" => "Kita Ikuyo", "anime_id" => 3, "doubleurs_id" => null, "image" => "kita.jpg", "description" => "Une première année de lycée brillante et populaire. Elle est en charge de la guitare et du chant du Kessoku Band. C'est un personnage joyeux qui aime interagir avec les gens et peut lui parler avec un sourire sans hésitation, même lorsqu'elle la rencontre pour la première fois. Elle aspire à Ryo et ses sentiments peuvent aller trop loin. Elle prend souvent des photos et les télécharge sur Isosta."],
            ["nom" => "Kokonoe Yae", "anime_id" => 14, "doubleurs_id" => null, "image" => "kokonoe.jpg", "description" => "Un samouraï du pays des dieux, Iishen. Ce n'est pas la personne la mieux élevée du moment et peut être plutôt maladroite, mais elle admire plutôt Touya et sa capacité à être humble et à choisir d'aider les autres, raison pour laquelle elle décide de le rejoindre dans le voyage."],
            ["nom" => "Kotarou Katsura", "anime_id" => 11, "doubleurs_id" => 8, "image" => "zura.jpg", "description" => "Katsura est l'ancien camarade de Gintoki pendant la guerre de Joi. Même après la prise de contrôle du Japon par Amanto, Katsura continue de résister à l'Amanto et a amassé un groupe d'adeptes. Son arme de prédilection est une grenade métallique. Il est recherché en raison de son implication dans des activités terroristes contre le Bakufu et est constamment en fuite du Shinsengumi."],
            ["nom" => "Kusuo Saiki", "anime_id" => 31, "doubleurs_id" => 11, "image" => "saiki.jpg", "description" => "Saiki a une personnalité extrêmement indifférente. En tant que médium doué qui peut faire tout ce qu'il veut, il a depuis longtemps cessé de se soucier du monde; cependant, il s'est montré extrêmement prudent, car il fuit souvent Nendou, la seule personne qu'il craint, et est enclin à se téléporter immédiatement dans des endroits éloignés en repérant un insecte."],
            ["nom" => "Kyoujurou Rengoku", "anime_id" => 9, "doubleurs_id" => 7, "image" => "rengoku.jpg", "description" => "Kyoujurou est un personnage secondaire majeur de Demon Slayer: Kimetsu no Yaiba et un personnage majeur de l'arc Mugen Train. Il est un Demon Slayer du Demon Slayer Corps et l'ancien Flame Hashira."],
            ["nom" => "Lawliet L", "anime_id" => 8, "doubleurs_id" => null, "image" => "l.jpg", "description" => "L, qui utilise également les pseudonymes Hideki Ryuga, Ryuzaki, Eraldo Coil et Deneuve, les deux derniers pour lesquels il s'est forgé une réputation de deuxième et troisième meilleurs détectives au monde, est assez secret et ne communique avec le monde qu'à travers son assistant Watari. Il ne montre jamais son visage au monde, au lieu de se représenter avec un L majuscule en police Cloister Black."],
            ["nom" => "Lean", "anime_id" => 14, "doubleurs_id" => null, "image" => "lean.jpg", "description" => "Un ancien du peuple des fées. Autoproclamé 612 ans. Lorsqu'elle est en public, elle cache ses ailes en utilisant la magie de la lumière. Est souvent accompagné de Paula; un ours en peluche qu'elle contrôle en utilisant sa magie d'attribut nul."],
            ["nom" => "Lelouch Lamperouge", "anime_id" => 7, "doubleurs_id" => 2, "image" => "lelouch.jpg", "description" => "Lelouch est un individu très intelligent qui est également calme, sophistiqué et arrogant en raison de son éducation aristocratique. À l'école, Lelouch se comporte comme un élève amical, sympathique et souvent facile à vivre. Cependant, c'est un masque pour cacher sa vraie nature. Alors qu'en tant que Zero, sa vraie nature est exprimée. Son charisme et ses croyances en la justice lui valent la confiance et le respect de nombreux soldats et dirigeants."],
            ["nom" => "Linse Shileska", "anime_id" => 14, "doubleurs_id" => null, "image" => "linse.jpg", "description" => "Une Mage plutôt timide, qui est le plus jeune jumeau d'Elze. Elle est du genre à préférer éviter les conflits inutiles et essaie de ne pas causer de problèmes inutiles, mais elle n'est pas opposée à demander de l'aide quand elle en a besoin."],
            ["nom" => "Mai Sakurajima", "anime_id" => 25, "doubleurs_id" => 19, "image" => "mai.jpg", "description" => "Mai est une personne sérieuse, en particulier autour de Sakuta Azusagawa. Elle est très sensible, polie, pondérée, serviable et gentille. Elle n'est pas dure par défaut, mais elle peut facilement s'énerver et apparaître comme un peu vive ou violente, en particulier pour Sakuta. Mai a tendance à ignorer et à étouffer les sentiments désagréables plutôt que de les gérer."],
            ["nom" => "Makima", "anime_id" => 5, "doubleurs_id" => 13, "image" => "makima.jpg", "description" => "Makima est un chasseur de diables de la sécurité publique.Il est révélé plus tard que Makima est, en réalité, le diable de contrôle.Makima est un fan extrême du diable à la tronçonneuse et, par procuration, Denji. Fascinée par sa capacité à anéantir le concept incarné d'un diable en les mangeant, son objectif est de mettre le diable à la tronçonneuse sous son contrôle, en utilisant son pouvoir pour créer un monde 'idéal' sans peurs."],
            ["nom" => "Megumin", "anime_id" => 17, "doubleurs_id" => 21, "image" => "megumi.jpg", "description" => "Un sorcier archi descendant de démons cramoisis; des humanoïdes puissants qui possèdent des cheveux noirs et des yeux rouges, et des caractéristiques de sport chuunibyou. Megumin ne connaît qu'une seule compétence, la magie d'explosion incroyablement puissante qui la neutralise immédiatement pour le reste de la journée lorsqu'elle est lancée, et refuse d'apprendre d'autres compétences."],
            ["nom" => "Mei Aihara", "anime_id" => 6, "doubleurs_id" => null, "image" => "mei.jpg", "description" => "Mei est une étudiante honorée, la petite-fille du président et la présidente du conseil étudiant. Elle est sévère, froide et souvent calme et posée, mais elle peut être plutôt sensible et mature dans une certaine mesure. Bien que Mei semble difficile à approcher, elle est plutôt sensible et solitaire, ce qui donne envie à Yuzu de s'occuper davantage de Mei."],
            ["nom" => "Mihari Oyama", "anime_id" => 23, "doubleurs_id" => null, "image" => "mihari.jpg", "description" => "La petite sœur de Mahiro, la fille responsable de la transformation de son frère aîné en fille. Elle le surveille et l'encadre dans sa nouvelle vie de fille."],
            ["nom" => "Miku Nakano", "anime_id" => 32, "doubleurs_id" => null, "image" => "miku.jpg", "description" => "Miku Nakano est la troisième soeur des Quintuplées Nakano. C'est une fille silencieuse et réservée. Miku a tendance à avoir une attitude pessimiste et peu de confiance en elle-même."],
            ["nom" => "Milim Nava", "anime_id" => 30, "doubleurs_id" => 6, "image" => "milim.jpg", "description" => "Le Seigneur Démon Milim Nava. C'est une dragonoïde. Et la reine la plus forte. Son surnom, Destroyer n'est pas seulement pour le spectacle. C'est un seigneur démon contre lequel il ne faut jamais se battre, surnommé Destruction lui-même. Elle fait partie des seigneurs démons des huit étoiles."],
            ["nom" => "Miyuki Shirogane", "anime_id" => 16, "doubleurs_id" => 3, "image" => "miyuki.jpg", "description" => "Monstrueusement intelligent, se classant parmi les meilleurs du pays aux examens simulés, il est également doué en gestion, il est donc respecté par les autres comme un génie, mais il est plus correct de dire qu'il est accro au travail acharné.Il ne refusera jamais une occasion d'écouter les gens qui viennent lui parler ou leur rendre service, et s'investit sincèrement dans le bien-être des autres."],
            ["nom" => "Mochizuki Touya", "anime_id" => 14, "doubleurs_id" => null, "image" => "touya.jpg", "description" => "Garçon de 15 ans qui a été accidentellement frappé par la foudre, par l'erreur de Dieu. Comme acte d'expiation, Dieu ressuscite Touya dans un monde différent. Donc Touya ne meurt pas très facilement dans ce nouveau monde plus conflictuel, Dieu lui donne de multiples avantages, tels que la possibilité d'utiliser tous les sorts magiques, et une vaste réserve de mana pour le soutenir, en plus Dieu a augmenté sa mémoire, son endurance , réflexes, etc."],
            ["nom" => "Nakano Itsuki", "anime_id" => 32, "doubleurs_id" => 14, "image" => "itsuki.jpg", "description" => "Itsuki Nakano est la cinquième sœur des Quintuplées Nakano. Elle est attribuée comme la \"première fille\" de la série. Itsuki est sérieuse et diligente, mais elle est aussi gloutonne et pleurnicharde."],
            ["nom" => "Oyama Mahiro", "anime_id" => 23, "doubleurs_id" => null, "image" => "mahiro.jpg", "description" => "Le protagoniste d'Onii-chan wa Oshimai. Il a été transformé en fille grâce à sa petite sœur en le droguant."],
            ["nom" => "Ram", "anime_id" => 26, "doubleurs_id" => 16, "image" => "ram.jpg", "description" => "Ram est l'une des femmes de ménage jumelles travaillant pour Roswaal L Mathers. Elle est apparemment égocentrique et fait les choses à son propre rythme, cependant, en réalité, elle se tient à distance des gens pour les vérifier. Elle croit que Roswaal est le plus grand et que personne d'autre n'est aussi précieux, à l'exception de sa sœur Rem."],
            ["nom" => "Raphtalia", "anime_id" => 33, "doubleurs_id" => 19, "image" => "raphatalia.jpg", "description" => "Elle a subi des changements importants tout au long de l'histoire. Lorsque Raphtalia est présentée pour la première fois, c'est une enfant qui a les cheveux longs et non coiffés et une robe en tissu sale. Après avoir été acheté par Naofumi, il lui a coupé les cheveux à une longueur acceptable, lui a donné un bain et lui a acheté un ensemble de vêtements beaucoup plus approprié pour partir à l'aventure."],
            ["nom" => "Reita Toritsuka", "anime_id" => 31, "doubleurs_id" => 5, "image" => "toritsuka.jpg", "description" => "Un autre médium et l'une des trois personnes extérieures à la famille de Saiki connaissant ses capacités. Il a la capacité de voir les esprits et est hanté par le fantôme du défunt père de Nendou, mais ne s'intéresse qu'à utiliser sa capacité à attirer les filles."],
            ["nom" => "Rem", "anime_id" => 26, "doubleurs_id" => 14, "image" => "rem.jpg", "description" => "Rem est l'une des femmes de ménage jumelles travaillant pour Roswaal L Mathers. Elle a tendance à parler d'une manière superficiellement polie et agit parfois sans réfléchir. Elle tient à la fois le respect d'adoration et la culpabilité envers sa sœur pour un incident dans le passé; à cause de cela, Rem a tendance à se considérer comme inférieure."],
            ["nom" => "Riki Nendou", "anime_id" => 31, "doubleurs_id" => 18, "image" => "nendo.jpg", "description" => "Nendo a une façon simple de penser, mais à cause de cela, Saiki est incapable de lire dans ses pensées. Parce que Saiki est incapable de détecter la présence de Nendo, Nendo est la seule personne capable de se faufiler sur Saiki et de lui faire croire qu'il sera un jour un ennemi dangereux. Nendou adore utiliser QtDesigner pour programmer des applications en Python."],
            ["nom" => "Rintarou Okabe", "anime_id" => 27, "doubleurs_id" => 15, "image" => "okabe.jpg", "description" => "Okabe est un individu théâtral et excentrique. C'est un savant fou autoproclamé, qui aime prendre son 'vrai nom' Kyouma Hououin et l'utilise souvent pour se présenter aux autres. Okabe aime se faire passer pour un agent travaillant contre une 'Organisation' spécifique, qui, selon lui, est toujours après lui, car il pense que ce type d'image lui confère une aura excellente et mystérieuse."],
            ["nom" => "Ryuk", "anime_id" => 8, "doubleurs_id" => null, "image" => "ryuk.jpg", "description" => "Le Shinigami original qui a laissé tomber le Death Note dans le monde humain, et aime aussi les pommes, que Light ramasserait. Agissant par pur ennui, Ryuk commence l'histoire de Death Note sur un coup de tête. Peut-être neutre par nature, Ryuk refuse souvent d'aider Light et aime plutôt le regarder lutter pour son objectif."],
            ["nom" => "Saitama", "anime_id" => 22, "doubleurs_id" => 3, "image" => "saitama.jpg", "description" => "Saitama est le héros le plus puissant du monde. S'étant apparemment entraîné à une condition surhumaine, Saitama fait face à une crise existentielle car il est maintenant trop puissant pour tirer le moindre frisson de ses actes héroïques.Il est enregistré auprès de la Heroes Association en tant que super-héros de classe C et est chargé de défendre Z-City contre des êtres mystérieux."],
            ["nom" => "Satoru Gojou", "anime_id" => 15, "doubleurs_id" => 17, "image" => "gojo.jpg", "description" => "Satoru Gojou est professeur de première année au Tokyo Metropolitan Magic Technical College.Lorsqu'il interagit avec ses élèves et ses amis, il est connu pour être assez joueur et insouciant. Cependant, envers ses ennemis, il s'est montré assez cruel et rebelle. Il est également très confiant dans ses capacités et sa réputation de puissant sorcier."],
            ["nom" => "Shouko Nishimiya", "anime_id" => 1, "doubleurs_id" => null, "image" => "shouko.jpg", "description" => "Un jeune étudiant sourd transféré avec une vision incroyablement positive de la vie. Bien qu'elle soit victime d'intimidation continue, elle garde toujours le sourire aux lèvres."],
            ["nom" => "Tedexa Rize", "anime_id" => null, "doubleurs_id" => null, "image" => "rize.jpg", "description" => "Rize est une fille dure et entêtée. Elle détient secrètement une insécurité de ne pas s'intégrer et peut parfois se sentir seule; par exemple, alors qu'elle est une personne indépendante et physiquement forte, elle essaie d'agir comme une adolescente moyenne (allant même jusqu'à prétendre qu'elle ne peut pas soulever un sac de grains de café) afin qu'elle puisse apparaître plus proche d'elle amis. Rize peut être franc avec ses opinions et agit souvent comme la voix du bon sens dans le groupe."],
            ["nom" => "Tsukuyo", "anime_id" => 11, "doubleurs_id" => 10, "image" => "tsukuyo.jpg", "description" => "Tsukuyo est une femme aux cheveux blonds avec une cicatrice sur le front et la joue gauche. L'une des plus connues Hundred Blooms of Yoshiwara, une équipe d'application de la loi de Yoshiwara composée de toutes les femmes, déployée par le Night King Hosen. Bien qu'elle semble être une personne sans cœur lorsqu'elle est approchée par Odd Jobs lorsqu'il arrive à Yoshiwara, jetant un faux kunai sur leur front, elle devient plus tard amie avec eux."],
            ["nom" => "Ujimatsu Chiya", "anime_id" => null, "doubleurs_id" => null, "image" => "chiya.jpg", "description" => "Le camarade de classe de Cocoa au lycée, dont la famille gère son propre café, Ama Usa An, qui a sa propre mascotte de lapin nommée Anko. Chiya est très douce et distinguée, et est généralement le gardien de la paix. Elle aime donner aux bonbons japonais du café de sa famille des noms longs et délicats, comme \"Joyau rouge dans un champ enneigé\" et \"Lune et étoiles reflétées sur la mer\". Bien qu'elle semble douce en surface, elle aime raconter des histoires de fantômes et déranger ses amis."],
            ["nom" => "Urnea Belfast Yumina", "anime_id" => 14, "doubleurs_id" => null, "image" => "yumina.jpg", "description" => "La future épouse de Touya; qui est la fille unique du roi et la cousine aînée de Sushie. Un utilisateur d'arc et possesseur de mauvais yeux, qui peut discerner la vraie nature d'une personne."],
            ["nom" => "Yagami Light", "anime_id" => 8, "doubleurs_id" => null, "image" => "yagami.jpg", "description" => "Light, né le 28 février 1986, est un élève de troisième année du secondaire (12e année) à la Daikoku Private Academy (大国学園, Daikoku Gakuen) qui suit également des cours supplémentaires à la Gamou Prep Academy au début de l'histoire. Light a un père, Soichiro Yagami, qui est le chef de la police. Light a également une mère, Sachiko Yagami, et une sœur cadette, Sayu Yagami."],
            ["nom" => "Yamada Ryou", "anime_id" => 3, "doubleurs_id" => null, "image" => "yamada.jpg", "description" => "Une deuxième année de lycée cool et solitaire. Elle est en charge de la basse du Kessoku Band. C'est la meilleure amie de Nijika. Ses passe-temps sortent de l'ordinaire et elle se réjouit lorsqu'elle est traitée de cinglée. Elle vit dans une famille aisée, mais elle dépense une grande partie de son argent en instruments et est toujours à court d'argent. Elle mange occasionnellement de l'herbe pour se débarrasser de sa faim."]
        ]);
    }
}
